# Generated by Django 2.0.2 on 2019-07-14 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('account_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ifsc_code', models.CharField(max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('bank_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_spent', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.CharField(max_length=500)),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger_admin.Bank')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_earned', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.CharField(max_length=500)),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger_admin.Bank')),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_invested', models.DecimalField(decimal_places=2, max_digits=20)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('bank_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger_admin.BankDetail')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentType',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Trading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_invested', models.DecimalField(decimal_places=2, max_digits=20)),
                ('type_details', models.CharField(max_length=500)),
                ('bank_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger_admin.BankDetail')),
            ],
        ),
        migrations.CreateModel(
            name='TradingInvestment',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='trading',
            name='trading_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger_admin.TradingInvestment'),
        ),
        migrations.AddField(
            model_name='investment',
            name='investment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger_admin.InvestmentType'),
        ),
        migrations.AddField(
            model_name='bank',
            name='bank_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger_admin.BankDetail'),
        ),
    ]
